echo allowFlight=false >> server.properties
echo allowNether=true >> server.properties
echo broadcastConsoleToOPs=true >> server.properties
echo broadcastRCONToOPs=true >> server.properties
echo difficulty=normal >> server.properties
echo enableJMXMonitoring=false >> server.properties
echo enableCommandBlock=false >> server.properties
echo enableQuery=false >> server.properties
echo enableRCON=false >> server.properties
echo enableStatus=true >> server.properties
echo enforceWhitelist=false >> server.properties
echo entityBroadcastRangePercentage=100 >> server.properties
echo forceGamemode=false >> server.properties
echo functionPermissionLevel=2 >> server.properties
echo gamemode=survival >> server.properties
echo generatorSettings >> server.properties
echo generateStructures=true >> server.properties
echo hardcore=false >> server.properties
echo levelName=World >> server.properties
echo levelSeed >> server.properties
echo levelType=default >> server.properties
echo maxBuildHeight=256 >> server.properties
echo maxPlayers=20 >> server.properties
echo maxTickTime=60000 >> server.properties
echo maxWorldSize=29999984 >> server.properties
echo motd="A Minecraft Server" >> server.properties
echo networkCompressionThreshold=256 >> server.properties
echo onlineMode=true >> server.properties
echo OPPermissionLevel=4 >> server.properties
echo playerIdleTimeout=0 >> server.properties
echo preventProxyConnections=false >> server.properties
echo pvp=true >> server.properties
echo queryPort=25565 >> server.properties
echo rateLimit=0 >> server.properties
echo rconPassword >> server.properties
echo rconPort=25575 >> server.properties
echo resourcePack >> server.properties
echo resourcePackSHA1 >> server.properties
echo serverIP >> server.properties
echo serverPort=25565 >> server.properties
echo snooperEnabled=true >> server.properties
echo spawnAnimals=true >> server.properties
echo spawnMonsters=true >> server.properties
echo spawnNPCs=true >> server.properties
echo spawnProtection=16 >> server.properties
echo syncChunkWrites=true >> server.properties
echo textFilteringConfig >> server.properties
echo useNativeTransport=true >> server.properties
echo viewDistance=12 >> server.properties
echo whiteList=false >> server.properties
echo xms=1024m >> server.properties
echo xmx=2048m >> server.properties
